'''
Created on Nov 26, 2013

@author: schernikov
'''
nameset = [
    ["1","IN_BYTES","octetDeltaCount","Incoming flow bytes (src->dst)"],
    ["2","IN_PKTS","packetDeltaCount","Incoming flow packets (src->dst)"],
    ["3","FLOWS","","Number of flows"],
    ["4","PROTOCOL","protocolIdentifier","IP protocol byte"],
    ["58500","PROTOCOL_MAP","","IP protocol name"],
    ["5","SRC_TOS","ipClassOfService","Type of service byte"],
    ["6","TCP_FLAGS","tcpControlBits","Cumulative of all flow TCP flags"],
    ["7","L4_SRC_PORT","sourceTransportPort","IPv4 source port"],
    ["58503","L4_SRC_PORT_MAP","","Layer 4 source port symbolic name"],
    ["8","IPV4_SRC_ADDR","sourceIPv4Address","IPv4 source address"],
    ["9","IPV4_SRC_MASK","sourceIPv4PrefixLength","IPv4 source subnet mask (/<bits>)"],
    ["10","INPUT_SNMP","ingressInterface","Input interface SNMP idx"],
    ["11","L4_DST_PORT","destinationTransportPort","IPv4 destination port"],
    ["58507","L4_DST_PORT_MAP","","Layer 4 destination port symbolic name"],
    ["58508","L4_SRV_PORT","","Layer 4 server port"],
    ["58509","L4_SRV_PORT_MAP","","Layer 4 server port symbolic name"],
    ["12","IPV4_DST_ADDR","destinationIPv4Address","IPv4 destination address"],
    ["13","IPV4_DST_MASK","destinationIPv4PrefixLength","IPv4 dest subnet mask (/<bits>)"],
    ["14","OUTPUT_SNMP","egressInterface","Output interface SNMP idx"],
    ["15","IPV4_NEXT_HOP","ipNextHopIPv4Address","IPv4 next hop address"],
    ["16","SRC_AS","bgpSourceAsNumber","Source BGP AS"],
    ["17","DST_AS","bgpDestinationAsNumber","Destination BGP AS"],
    ["21","LAST_SWITCHED","flowEndSysUpTime","SysUptime (msec) of the last flow pkt"],
    ["22","FIRST_SWITCHED","flowStartSysUpTime","SysUptime (msec) of the first flow pkt"],
    ["23","OUT_BYTES","postOctetDeltaCount","Outgoing flow bytes (dst->src)"],
    ["24","OUT_PKTS","postPacketDeltaCount","Outgoing flow packets (dst->src)"],
    ["27","IPV6_SRC_ADDR","sourceIPv6Address","IPv6 source address"],
    ["28","IPV6_DST_ADDR","destinationIPv6Address","IPv6 destination address"],
    ["29","IPV6_SRC_MASK","sourceIPv6PrefixLength","IPv6 source mask"],
    ["30","IPV6_DST_MASK","destinationIPv6PrefixLength","IPv6 destination mask"],
    ["32","ICMP_TYPE","icmpTypeCodeIPv4","ICMP Type * 256 + ICMP code"],
    ["34","SAMPLING_INTERVAL","","Sampling rate"],
    ["35","SAMPLING_ALGORITHM","","Sampling type (deterministic/random)"],
    ["36","FLOW_ACTIVE_TIMEOUT","flowActiveTimeout","Activity timeout of flow cache entries"],
    ["37","FLOW_INACTIVE_TIMEOUT","flowIdleTimeout","Inactivity timeout of flow cache entries"],
    ["38","ENGINE_TYPE","","Flow switching engine"],
    ["39","ENGINE_ID","","Id of the flow switching engine"],
    ["40","TOTAL_BYTES_EXP","exportedOctetTotalCount","Total bytes exported"],
    ["41","TOTAL_PKTS_EXP","exportedMessageTotalCount","Total flow packets exported"],
    ["42","TOTAL_FLOWS_EXP","exportedFlowRecordTotalCount","Total number of exported flows"],
    ["52","MIN_TTL","minimumTTL","Min flow TTL"],
    ["53","MAX_TTL","maximumTTL","Max flow TTL"],
    ["56","IN_SRC_MAC","sourceMacAddress","Source MAC Address"],
    ["58","SRC_VLAN","vlanId","Source VLAN"],
    ["59","DST_VLAN","postVlanId","Destination VLAN"],
    ["60","IP_PROTOCOL_VERSION","ipVersion",""],
    ["61","DIRECTION","flowDirection","It indicates where a sample has been taken (always 0)"],
    ["62","IPV6_NEXT_HOP","ipNextHopIPv6Address","IPv6 next hop address"],
    ["70","MPLS_LABEL_1","mplsTopLabelStackSection","MPLS label at position 1"],
    ["71","MPLS_LABEL_2","mplsLabelStackSection2","MPLS label at position 2"],
    ["72","MPLS_LABEL_3","mplsLabelStackSection3","MPLS label at position 3"],
    ["73","MPLS_LABEL_4","mplsLabelStackSection4","MPLS label at position 4"],
    ["74","MPLS_LABEL_5","mplsLabelStackSection5","MPLS label at position 5"],
    ["75","MPLS_LABEL_6","mplsLabelStackSection6","MPLS label at position 6"],
    ["76","MPLS_LABEL_7","mplsLabelStackSection7","MPLS label at position 7"],
    ["77","MPLS_LABEL_8","mplsLabelStackSection8","MPLS label at position 8"],
    ["78","MPLS_LABEL_9","mplsLabelStackSection9","MPLS label at position 9"],
    ["79","MPLS_LABEL_10","mplsLabelStackSection10","MPLS label at position 10"],
    ["80","OUT_DST_MAC","destinationMacAddress","Destination MAC Address"],
    ["95","APPLICATION_ID","application_id","Cisco NBAR Application Id"],
    ["102","PACKET_SECTION_OFFSET","","Packet section offset"],
    ["103","SAMPLED_PACKET_SIZE","","Sampled packet size"],
    ["104","SAMPLED_PACKET_ID","","Sampled packet id"],
    ["130","EXPORTER_IPV4_ADDRESS","exporterIPv4Address","Exporter IPv4 Address"],
    ["131","EXPORTER_IPV6_ADDRESS","exporterIPv6Address","Exporter IPv6 Address"],
    ["148","FLOW_ID","flowId","Serial Flow Identifier"],
    ["150","FLOW_START_SEC","flowStartSeconds","Seconds (epoch) of the first flow packet"],
    ["151","FLOW_END_SEC","flowEndSeconds","Seconds (epoch) of the last flow packet"],
    ["152","FLOW_START_MILLISECONDS","flowStartMilliseconds","Msec (epoch) of the first flow packet"],
    ["153","FLOW_END_MILLISECONDS","flowEndMilliseconds","Msec (epoch) of the last flow packet"],
    ["239","BIFLOW_DIRECTION","biflow_direction","1=initiator, 2=reverseInitiator"],
    ["277","OBSERVATION_POINT_TYPE","","Observation point type"],
    ["300","OBSERVATION_POINT_ID","","Observation point id"],
    ["302","SELECTOR_ID","","Selector id"],
    ["304","IPFIX_SAMPLING_ALGORITHM","","Sampling algorithm"],
    ["309","SAMPLING_SIZE","","Number of packets to sample"],
    ["310","SAMPLING_POPULATION","","Sampling population"],
    ["312","FRAME_LENGTH","","Original L2 frame length"],
    ["318","PACKETS_OBSERVED","","Tot number of packets seen"],
    ["319","PACKETS_SELECTED","","Number of pkts selected for sampling"],
    ["335","SELECTOR_NAME","","Sampler name"],
]

def nmap(nset):
    res = {}
    for nms in nset:
        fix = nms[2]
        if not fix: continue
        res[fix] = nms
    return res

namesmap = nmap(nameset)
